/**
 * Diccionario central de textos visibles (UI) — Single Source of Truth.
 * Solo representación visible; no cambia lógica ni keys internos.
 */

export const UI_TEXT = {
  states: {
    flagged: "Requiere atención prioritaria",
    flaggedShort: "Requiere atención",
    modoUrgente: "Modo urgente",
    modoUrgenteActive: "Modo urgente activo",
    excepcionOperativa: "Excepción operativa",
  },
  labels: {
    bypassColumn: "Modo urgente",
    flaggedColumn: "Requiere atención prioritaria",
    validarExcepcion: "Validar excepción",
    revocarExcepcion: "Revocar excepción",
    validar: "✓ Validar",
    revocar: "✕ Revocar",
    motivoCierre: "Motivo de cierre",
    fundamentoObligatorio: "Fundamento obligatorio...",
    caseTimelineTitle: "LÍNEA DE TIEMPO",
    instructionsTitle: "INSTRUCCIONES",
    instructionsEmpty: "Sin instrucciones activas.",
    evidenceTitle: "EVIDENCIA",
    commentTitle: "COMENTARIO",
    instructionCreateTitle: "CREAR INSTRUCCIÓN",
    scopeLabel: "Alcance",
    audienceLabel: "Audiencia",
    summaryLabelRequired: "Resumen (obligatorio)",
    detailsLabelOptional: "Detalles (opcional)",
    evidenceLabelEnterToAdd: "Evidencia (Enter para agregar)",
    statusAcked: "ACUSADA",
    statusPending: "PENDIENTE",
    scopeLocal: "LOCAL",
    scopeComunal: "COMUNAL",
    scopeRegional: "REGIONAL",
    audienceBoth: "AMBOS",
    audiencePese: "PESE",
    audienceDelegado: "DELEGADO",
    impactLevelLabel: "Impacto",
    impactL1: "L1 — Operativa local",
    impactL2: "L2 — Procedimental sensible",
    impactL3: "L3 — Crítica",
    scopeFunctionalLabel: "Ámbito",
    scopeOperaciones: "Operaciones",
    scopeFiscalizacion: "Fiscalización",
    scopeSeguridad: "Seguridad",
    scopeTI: "TI",
    scopeInfraestructura: "Infraestructura",
    scopeOtro: "Otro",
    bypassLabel: "Bypass (excepción)",
    bypassReasonPlaceholder: "Motivo obligatorio (mín. 30 caracteres)",
    instructionBypassBadge: "EXCEPCIÓN (BYPASS)",
    instructionCreated: "Instrucción creada",
    instructionAck: "Acuse de instrucción",
    instructionClosed: "Instrucción cerrada",
    instructionUnavailable: "Instrucción no disponible",
    instructionReplyLabel: "Respuesta a instrucción",
    trustPanelTitle: "Firma y confianza",
    trustStatusTitle: "Estado de verificación",
    trustTrustedListTitle: "Firmantes confiables",
    trustAliasLabel: "Alias",
    trustFingerprintLabel: "Huella",
    trustAddTitle: "Agregar firmante confiable",
    trustPublicKeyLabel: "Clave pública",
    trustReasonLabel: "Motivo",
  },
  labelsCc: {
    ccReadOnly: "Con copia:",
    ccLabel: "Con copia (CC)",
    ccPlaceholder: "Ej: Dirección Regional / Jurídica / Logística",
  },
  tooltips: {
    modoUrgente:
      "Permite registrar situaciones que requieren acción inmediata sin completar todos los campos estándar. Su uso queda registrado para revisión posterior.",
    ackConfirmReceipt: "Confirmar que recibiste esta instrucción.",
    caseCreateInstruction: "Genera instrucción con acuse obligatorio.",
  },
  errors: {
    generic: "Se produjo un inconveniente interno. Intente nuevamente.",
    validation: "Revise los datos ingresados.",
    unauthorized: "No cuenta con autorización para esta acción.",
    network: "No se pudo establecer conexión. Intente nuevamente.",
    recepcionarPrimero: "Recepcionar el caso primero.",
    excepcionRequiereValidacion: "Excepción operativa requiere validación.",
    alMenosUnaAccion: "Se requiere al menos una acción.",
    alMenosUnaDecision: "Se requiere al menos una decisión.",
    casoDebeEstarResuelto: "El caso debe estar en 'Resuelto' antes de cerrar.",
    ingresaMotivoCierre: "Ingrese el motivo de cierre.",
    soloDirectorValida: "Solo el Director Regional puede validar la excepción.",
    fundamentoRequerido: "Se requiere fundamento.",
    nombreObligatorio: "Nombre obligatorio.",
    seleccioneComuna: "Seleccione una comuna.",
    instructionSummaryRequired: "Debes ingresar un resumen.",
    bypassReasonMin: "El motivo de bypass debe tener al menos 30 caracteres.",
    l3RequiresBypass: "L3 excede tu nivel — requiere BYPASS con motivo.",
    signFailed: "No se pudo firmar. Intente nuevamente.",
    signKeyCreateFailed: "No se pudo crear la clave de firma.",
    signPassphraseMismatch: "La contraseña no coincide.",
    importFileTooLarge: "El archivo es demasiado grande.",
    importInvalidJson: "Archivo no es JSON válido.",
    importUntrustedConfirmFailed: "No se pudo confirmar la clave. Intente nuevamente.",
    trustAddInvalid: "Revisa alias, clave pública y motivo.",
    trustAddFailed: "No se pudo agregar el firmante.",
    trustRemoveFailed: "No se pudo quitar el firmante.",
  },
  buttons: {
    minutaCopiada: "Minuta copiada",
    ackConfirmReceipt: "Confirmar recepción",
    addComment: "Agregar comentario",
    caseCreateInstruction: "Crear instrucción",
    closeInstruction: "Cerrar instrucción",
    replyToInstruction: "Responder",
    sendReply: "Enviar",
    addCc: "+ Agregar copia",
    removeCc: "Quitar",
    exportState: "Exportar",
    importState: "Importar",
  },
  warnings: {
    centralToPeseOrDelegado: "Advertencia: instrucción desde Nivel Central a PESE/DELEGADO.",
  },
  misc: {
    reporteBypassLabel: "Modo urgente",
    validacionExpost: "Requiere validación posterior",
    excepcionSinFundamentoObjetivo: "Excepción operativa sin fundamento objetivo → Requiere atención prioritaria",
    confirmarExcepcionOperativa: "Confirmo que esta situación requiere excepción operativa.",
    commentPlaceholder: "Comentario...",
    instructionSummaryPlaceholder: "Ej: Mantener mesa operativa, informar novedades cada 15 min.",
    instructionDetailsPlaceholder: "Antecedentes ampliados, contexto, referencias.",
    instructionReplyPlaceholder: "Ej: Recibido, en ejecución / Hecho / No es posible por X",
    instructionReplySaved: "Respuesta registrada en timeline",
    evidencePlaceholder: "URL o descripción",
    commentSaved: "Comentario registrado",
    signPassphrasePrompt: "Ingrese contraseña para firma",
    exportUnsignedWarning: "Export sin firma.",
    noSigningKeyConfirm: "No hay clave de firma configurada. ¿Continuar sin firmar?",
    signCreatePassphrase1: "Crear contraseña para la clave de firma",
    signCreatePassphrase2: "Repita la contraseña",
    signKeyCreated: "Clave de firma creada.",
    exportOk: "Export realizado correctamente.",
    importOk: "Import realizado correctamente.",
    importUnsignedWarning: "El import no está firmado.",
    trustConfirmWord: "Confirmar",
    importUntrustedTypeToConfirm: "El export está firmado por una clave no confiable. ¿Agregar a confiables?",
    importSignedTrustedOk: "Import con firma válida (confiable).",
    importConfirm: "Esto reemplazará los casos actuales. ¿Continuar?",
    trustRecommendationNoSupport: "Usar sin firma.",
    trustRecommendationNoKey: "Crear llave para firmar exports.",
    trustRecommendationOk: "Puedes firmar y verificar autoría.",
    trustAddedOk: "Firmante agregado a confianza.",
    trustRemovedOk: "Firmante eliminado de confianza.",
    trustVerificationAvailable: "Disponible",
    trustVerificationUnavailable: "No disponible",
    trustLocalKeyConfigured: "Configurada",
    trustLocalKeyNotConfigured: "No configurada",
    trustUnavailable: "Esta verificación no está disponible en este navegador.",
    trustAddButton: "➕ Agregar a confianza",
    importSignedTrustedOkShort: "Import con autoría verificada (confiable).",
    importUnsignedWarningShort: "Import permitido sin verificación de autoría.",
  },
} as const;
