/**
 * Diccionario central de textos visibles (UI) — Single Source of Truth.
 * Solo representación visible; no cambia lógica ni keys internos.
 */

export const UI_TEXT = {
  states: {
    flagged: "Requiere atención prioritaria",
    flaggedShort: "Requiere atención",
    modoUrgente: "Modo urgente",
    modoUrgenteActive: "Modo urgente activo",
    excepcionOperativa: "Excepción operativa",
  },
  labels: {
    bypassColumn: "Modo urgente",
    flaggedColumn: "Requiere atención prioritaria",
    validarExcepcion: "Validar excepción",
    revocarExcepcion: "Revocar excepción",
    validar: "✓ Validar",
    revocar: "✕ Revocar",
    motivoCierre: "Motivo de cierre",
    fundamentoObligatorio: "Fundamento obligatorio...",
    caseTimelineTitle: "LÍNEA DE TIEMPO",
    instructionsTitle: "INSTRUCCIONES",
    instructionsEmpty: "Sin instrucciones activas.",
    evidenceTitle: "EVIDENCIA",
    commentTitle: "COMENTARIO",
    instructionCreateTitle: "CREAR INSTRUCCIÓN",
    scopeLabel: "Alcance",
    audienceLabel: "Audiencia",
    summaryLabelRequired: "Resumen (obligatorio)",
    detailsLabelOptional: "Detalles (opcional)",
    evidenceLabelEnterToAdd: "Evidencia (Enter para agregar)",
    statusAcked: "ACUSADA",
    statusPending: "PENDIENTE",
    scopeLocal: "LOCAL",
    scopeComunal: "COMUNAL",
    scopeRegional: "REGIONAL",
    audienceBoth: "AMBOS",
    audiencePese: "PESE",
    audienceDelegado: "DELEGADO",
    impactLevelLabel: "Impacto",
    impactL1: "L1 — Operativa local",
    impactL2: "L2 — Procedimental sensible",
    impactL3: "L3 — Crítica",
    scopeFunctionalLabel: "Ámbito",
    scopeOperaciones: "Operaciones",
    scopeFiscalizacion: "Fiscalización",
    scopeSeguridad: "Seguridad",
    scopeTI: "TI",
    scopeInfraestructura: "Infraestructura",
    scopeOtro: "Otro",
    bypassLabel: "Bypass (excepción)",
    bypassReasonPlaceholder: "Motivo obligatorio (mín. 30 caracteres)",
    instructionBypassBadge: "EXCEPCIÓN (BYPASS)",
    instructionReplyLabel: "Respuesta a instrucción",
    instructionUnavailable: "Instrucción no disponible",
    instructionCreated: "Instrucción creada",
    instructionAck: "Acuse de instrucción",
    instructionClosed: "Instrucción cerrada",
    trustPanelTitle: "Firma y confianza",
    trustStatusTitle: "Estado de verificación",
    trustTrustedListTitle: "Firmantes confiables",
    trustAddTitle: "Agregar firmante confiable",
    trustAliasLabel: "Alias",
    trustPublicKeyLabel: "Clave pública",
    trustReasonLabel: "Motivo",
    trustFingerprintLabel: "Huella",
  },
  tooltips: {
    modoUrgente:
      "Permite registrar situaciones que requieren acción inmediata sin completar todos los campos estándar. Su uso queda registrado para revisión posterior.",
    ackConfirmReceipt: "Confirmar que recibiste esta instrucción.",
    caseCreateInstruction: "Genera instrucción con acuse obligatorio.",
  },
  warnings: {
    centralToPeseOrDelegado:
      "Advertencia: una instrucción desde Nivel Central dirigida a PESE/DELEGADO requiere especial cuidado (conducto y coordinación).",
  },
  errors: {
    generic: "Se produjo un inconveniente interno. Intente nuevamente.",
    validation: "Revise los datos ingresados.",
    unauthorized: "No cuenta con autorización para esta acción.",
    network: "No se pudo establecer conexión. Intente nuevamente.",
    recepcionarPrimero: "Recepcionar el caso primero.",
    excepcionRequiereValidacion: "Excepción operativa requiere validación.",
    alMenosUnaAccion: "Se requiere al menos una acción.",
    alMenosUnaDecision: "Se requiere al menos una decisión.",
    casoDebeEstarResuelto: "El caso debe estar en 'Resuelto' antes de cerrar.",
    ingresaMotivoCierre: "Ingrese el motivo de cierre.",
    soloDirectorValida: "Solo el Director Regional puede validar la excepción.",
    fundamentoRequerido: "Se requiere fundamento.",
    nombreObligatorio: "Nombre obligatorio.",
    seleccioneComuna: "Seleccione una comuna.",
    instructionSummaryRequired: "Debes ingresar un resumen.",
    bypassReasonMin: "El motivo de bypass debe tener al menos 30 caracteres.",
    l3RequiresBypass: "L3 excede tu nivel — requiere BYPASS con motivo.",
    importInvalidJson: "Archivo no es JSON válido.",
    importFileTooLarge: "Archivo demasiado grande (máx. {maxMb} MB).",
    signFailed:
      "No se pudo firmar (passphrase incorrecta o llave inválida). Se exportará sin firma.",
    signKeyCreateFailed: "No se pudo crear la llave de firma.",
    signPassphraseMismatch: "Las passphrases no coinciden. Export se hará sin firma.",
    trustAddInvalid: "Revisa alias, clave pública y motivo.",
    trustAddFailed: "No se pudo agregar el firmante.",
    trustRemoveFailed: "No se pudo quitar el firmante.",
    importUntrustedConfirmFailed: "No se confirmó la confianza. Import cancelado.",
  },
  buttons: {
    minutaCopiada: "Minuta copiada",
    ackConfirmReceipt: "Confirmar recepción",
    addComment: "Agregar comentario",
    caseCreateInstruction: "Crear instrucción",
    replyToInstruction: "Responder",
    sendReply: "Enviar",
    addCc: "Agregar copia",
    removeCc: "Quitar",
    closeInstruction: "Cerrar instrucción",
    exportState: "Exportar",
    importState: "Importar",
  },
  labelsCc: {
    ccLabel: "Con copia (CC)",
    ccPlaceholder: "Ej: Dirección Regional / Jurídica / Logística",
    ccReadOnly: "Con copia:",
  },
  misc: {
    reporteBypassLabel: "Modo urgente",
    validacionExpost: "Requiere validación posterior",
    excepcionSinFundamentoObjetivo: "Excepción operativa sin fundamento objetivo → Requiere atención prioritaria",
    confirmarExcepcionOperativa: "Confirmo que esta situación requiere excepción operativa.",
    commentPlaceholder: "Comentario...",
    instructionSummaryPlaceholder: "Ej: Mantener mesa operativa, informar novedades cada 15 min.",
    instructionDetailsPlaceholder: "Antecedentes ampliados, contexto, referencias.",
    instructionReplyPlaceholder: "Ej: Recibido, en ejecución / Hecho / No es posible por X",
    instructionReplySaved: "Respuesta registrada en timeline",
    evidencePlaceholder: "URL o descripción",
    commentSaved: "Comentario registrado",
    exportOk: "Export listo.",
    importOk: "Import realizado.",
    importConfirm: "Esto reemplazará los casos actuales. ¿Continuar?",
    exportUnsignedWarning: "Export sin firma.",
    importUnsignedWarning:
      "Import sin firma: permitido, pero no hay garantía de autoría.",
    importUntrustedConfirm:
      "Firma válida, pero firmante NO está en la lista de confianza local. ¿Continuar igual?",
    importSignedTrustedOk: "Import con firma válida (confiable).",
    noSigningKeyConfirm:
      "No hay llave de firma configurada. ¿Deseas crear una ahora (recomendado)?",
    signPassphrasePrompt: "Ingrese passphrase para firmar el export:",
    signCreatePassphrase1: "Crea una passphrase (guárdala):",
    signCreatePassphrase2: "Repite la passphrase:",
    signKeyCreated: "Llave creada. Reintenta Exportar para firmar.",
    trustAddedOk: "Firmante agregado a confianza.",
    trustRemovedOk: "Firmante eliminado de confianza.",
    trustUnavailable: "Esta verificación no está disponible en este navegador.",
    trustConfirmWord: "CONFIAR",
    importUntrustedTypeToConfirm:
      "Firma válida, pero no confiable. Para continuar escribe CONFIAR:",
    trustVerificationAvailable: "Disponible",
    trustVerificationUnavailable: "No disponible",
    trustLocalKeyConfigured: "Configurada",
    trustLocalKeyNotConfigured: "No configurada",
    trustRecommendationNoSupport: "Usar sin firma.",
    trustRecommendationNoKey: "Crear llave para firmar exports.",
    trustRecommendationOk: "Puedes firmar y verificar autoría.",
    importSignedTrustedOkShort: "Import con autoría verificada (confiable).",
    importUnsignedWarningShort: "Import permitido sin verificación de autoría.",
    trustAddButton: "➕ Agregar a confianza",
  },

  recommendation: {
    FULL: {
      closed: {
        text: "Sin acciones",
        reason: "Estado Cerrado.",
      },
      criticalOverdue: {
        text: "Escalar a Nivel Central",
        reason: (el: number, sla: number) => `CRÍTICA+SLA vencido (${el}>${sla} min).`,
      },
      criticalInTime: {
        text: "Registrar acción inmediata",
        reason: (el: number, sla: number) => `CRÍTICA (SLA ${el}/${sla} min).`,
      },
      overdue: {
        text: "Registrar acción formal",
        reason: (el: number, sla: number) => `SLA vencido (${el}>${sla} min).`,
      },
      ok: {
        text: "Mantener monitoreo",
        reason: (el: number, sla: number) => `SLA dentro de margen (${el}/${sla} min).`,
      },
    },
    OP: {
      closed: {
        text: "Sin acciones",
        reason: "Caso cerrado.",
      },
      criticalOverdue: {
        text: "Escalar a Nivel Central",
        reason: "Atención inmediata: fuera de plazo.",
      },
      criticalInTime: {
        text: "Acción inmediata",
        reason: "Prioridad alta: actuar hoy.",
      },
      overdue: {
        text: "Registrar acción",
        reason: "Caso fuera de plazo: registrar gestión.",
      },
      ok: {
        text: "Mantener monitoreo",
        reason: "Seguir seguimiento.",
      },
    },
  },
} as const;
