/**
 * Diccionario central de textos visibles (UI) — Single Source of Truth.
 * Solo representación visible; no cambia lógica ni keys internos.
 */

export const UI_TEXT = {
  states: {
    flagged: "Requiere atención prioritaria",
    flaggedShort: "Requiere atención",
    modoUrgente: "Modo urgente",
    modoUrgenteActive: "Modo urgente activo",
    excepcionOperativa: "Excepción operativa",
  },
  labels: {
    bypassColumn: "Modo urgente",
    flaggedColumn: "Requiere atención prioritaria",
    validarExcepcion: "Validar excepción",
    revocarExcepcion: "Revocar excepción",
    validar: "✓ Validar",
    revocar: "✕ Revocar",
    motivoCierre: "Motivo de cierre",
    fundamentoObligatorio: "Fundamento obligatorio...",
    caseTimelineTitle: "LÍNEA DE TIEMPO",
    instructionsTitle: "INSTRUCCIONES",
    instructionsEmpty: "Sin instrucciones activas.",
    evidenceTitle: "EVIDENCIA",
    commentTitle: "COMENTARIO",
    instructionCreateTitle: "CREAR INSTRUCCIÓN",
    scopeLabel: "Alcance",
    audienceLabel: "Audiencia",
    summaryLabelRequired: "Resumen (obligatorio)",
    detailsLabelOptional: "Detalles (opcional)",
    evidenceLabelEnterToAdd: "Evidencia (Enter para agregar)",
    statusAcked: "ACUSADA",
    statusPending: "PENDIENTE",
    scopeLocal: "LOCAL",
    scopeComunal: "COMUNAL",
    scopeRegional: "REGIONAL",
    audienceBoth: "AMBOS",
    audiencePese: "PESE",
    audienceDelegado: "DELEGADO",
    impactLevelLabel: "Impacto",
    impactL1: "L1 — Operativa local",
    impactL2: "L2 — Procedimental sensible",
    impactL3: "L3 — Crítica",
    scopeFunctionalLabel: "Ámbito",
    scopeOperaciones: "Operaciones",
    scopeFiscalizacion: "Fiscalización",
    scopeSeguridad: "Seguridad",
    scopeTI: "TI",
    scopeInfraestructura: "Infraestructura",
    scopeOtro: "Otro",
    bypassLabel: "Bypass (excepción)",
    bypassReasonPlaceholder: "Motivo obligatorio (mín. 30 caracteres)",
    instructionBypassBadge: "EXCEPCIÓN (BYPASS)",
  },
  tooltips: {
    modoUrgente:
      "Permite registrar situaciones que requieren acción inmediata sin completar todos los campos estándar. Su uso queda registrado para revisión posterior.",
    ackConfirmReceipt: "Confirmar que recibiste esta instrucción.",
    caseCreateInstruction: "Genera instrucción con acuse obligatorio.",
  },
  errors: {
    generic: "Se produjo un inconveniente interno. Intente nuevamente.",
    validation: "Revise los datos ingresados.",
    unauthorized: "No cuenta con autorización para esta acción.",
    network: "No se pudo establecer conexión. Intente nuevamente.",
    recepcionarPrimero: "Recepcionar el caso primero.",
    excepcionRequiereValidacion: "Excepción operativa requiere validación.",
    alMenosUnaAccion: "Se requiere al menos una acción.",
    alMenosUnaDecision: "Se requiere al menos una decisión.",
    casoDebeEstarResuelto: "El caso debe estar en 'Resuelto' antes de cerrar.",
    ingresaMotivoCierre: "Ingrese el motivo de cierre.",
    soloDirectorValida: "Solo el Director Regional puede validar la excepción.",
    fundamentoRequerido: "Se requiere fundamento.",
    nombreObligatorio: "Nombre obligatorio.",
    seleccioneComuna: "Seleccione una comuna.",
    instructionSummaryRequired: "Debes ingresar un resumen.",
    bypassReasonMin: "El motivo de bypass debe tener al menos 30 caracteres.",
    l3RequiresBypass: "L3 excede tu nivel — requiere BYPASS con motivo.",
  },
  buttons: {
    minutaCopiada: "Minuta copiada",
    ackConfirmReceipt: "Confirmar recepción",
    addComment: "Agregar comentario",
    caseCreateInstruction: "Crear instrucción",
  },
  misc: {
    reporteBypassLabel: "Modo urgente",
    validacionExpost: "Requiere validación posterior",
    excepcionSinFundamentoObjetivo: "Excepción operativa sin fundamento objetivo → Requiere atención prioritaria",
    confirmarExcepcionOperativa: "Confirmo que esta situación requiere excepción operativa.",
    commentPlaceholder: "Comentario...",
    instructionSummaryPlaceholder: "Ej: Mantener mesa operativa, informar novedades cada 15 min.",
    instructionDetailsPlaceholder: "Antecedentes ampliados, contexto, referencias.",
    evidencePlaceholder: "URL o descripción",
    commentSaved: "Comentario registrado",
  },
} as const;
